### ISSUE TITLE
Changes website

### ISSUE THREAD

**Issue by juvogel** [locomojis/Chromoji#15]
when I try to login to [cas.iu.edu](http://cas.iu.edu/) for school it changes to the page to say "2013" that's it. I have already disabled it and confirmed it is the extension and nothing else.

**Comment by RobJDavey** [comment]
Thank you for reporting this! I had seen it once before buy could not reproduce it. That page seems to do it consistently so I should be able to find the issue now. :smiley:

**Comment by RobJDavey** [comment]
OK the good news is I know why this is happening.

The bad news is that this is because the website you linked uses very badly written code, and is not strictly a fault with Chromoji.

They are using `document.write()` in their production code. This works fine for them normally (e.g. when the page is still loading) however when we replace the &copy; sign in the same div with the correct emoji image, it causes the script to run a second time. Running a `document.write()` after the page has loaded will cause a new document to be created and this is why we are seeing nothing but the _2013_ they are writing.

I am already thinking of removing support for the &copy; symbol as well as a few other (e.g. &reg;, &trade;) symbols that iOS does not replace itself, but this will only fix it for sites that have this exact problem. Fixing the issue of badly written websites generally is a lot harder! :laughing:
