### ISSUE TITLE
User has missing emoji images

### ISSUE THREAD

**Issue by RobJDavey** [locomojis/Chromoji#21]
A user finds certain images are missing when looking at [this page](http://www.istartedsomething.com/uploads/emojisegoe.html).
![image](https://f.cloud.github.com/assets/884913/501386/37401356-bc97-11e2-86d1-cdab63bdc351.png)

So far I have not been able to reproduce this on Windows or Mac.

**Comment by m13253** [comment]
My OS and Chromium version:
![e6da13c7-33f4-4da9-ae2d-a17760d15ed9](https://f.cloud.github.com/assets/1808930/501598/d43d214a-bc9b-11e2-9663-075e11f53a8c.png)

The problem is still there at http://www.grumdrig.com/emoji-list/:
![acea11b3-8282-450c-8384-e542200c0190](https://f.cloud.github.com/assets/1808930/501576/424ff8ac-bc9b-11e2-87a1-f23fe08fa3d5.png)

When I right click on one of the broken images and select `Open in another window`, it comes a `ERR_FILE_NOT_FOUND` error:
![543829b6-974a-41ea-a505-6a541d5cc908](https://f.cloud.github.com/assets/1808930/501583/77a1a546-bc9b-11e2-839e-78f32d925413.png)

P.S.: I have already uninstalled the extension and reinstalled it. Still not working.

**Comment by RobJDavey** [comment]
I have a feeling I know what is causing this.
I'll try get a fix out for it later tonight.

Thanks for the extra information.

**Comment by RobJDavey** [comment]
I have just uploaded version 1.2.5. I believe this should fix it for you.
If you want to force an immediate update just go to chrome://extensions/ and tick the "Developer mode" checkbox, then click "Update extensions now". You won't seen any progress bar but it should update to the correct version after a minute or two.
If this doesn't fix the problem then let me know and I will reopen this issue.

**Comment by m13253** [comment]
Problem solved! Thanks!
And I have already modified my review on webstore.

P.S. I have also recommended this extension to my friends via G+. :-)

**Comment by RobJDavey** [comment]
Great to hear it's fixed... thanks for the help!
