### ISSUE TITLE
Add whitelist support

### ISSUE THREAD

**Issue by silkfire** [locomojis/Chromoji#28]
Could you add a whitelist support as well? That is, only allow Emoji rendering on specific domains. Cause I believe Chromoji takes up a lot of resources, I only want it to run on Facebook and Instagram.

Thank you for a great extension!

**Comment by RobJDavey** [comment]
I don't think this should be too difficult so I'll try have a look at it this weekend.

**Comment by mattgreen** [comment]
I keep running into random emoji on sites as well. Usually it is hilarious, but sometimes it is honestly difficult to read.

**Comment by locomojis** [comment]
It is fixed in the next version by not replacing certain characters which may result in conflict.
Also there's been a massive performance improvement which renders this issue resolved.

I only consider making the options page more difficult to understand with a certain feature, if there's enough interest for it.
