### ISSUE TITLE
Can't paste or inster emojis after installing the extension.

### ISSUE THREAD

**Issue by MariamAlsaraji** [locomojis/Chromoji#31]
As title.

**Comment by RobJDavey** [comment]
Please can you provide more detail, I'm not sure I fully understand what you mean?
Written instructions of what exactly you are doing and expecting to see will help a lot.

**Comment by MariamAlsaraji** [comment]
I'm using chrome on Mac. When the extension is inactivated or uninstalled I
can copy emojis from iemoji.com and paste them in Twitter. However when the
extension us activated I am unable to paste any emoji I copied.

**Comment by RobJDavey** [comment]
OK thanks, I'll investigate this soon and get back to you if/when I have a fix.

**Comment by MariamAlsaraji** [comment]
Thank you very much.

**Comment by ticky** [comment]
This is because Chromoji replaces emoji characters with images. If you are on OS X Lion or later, you should turn off Chromoji as the OS can handle emoji natively.

If you are on an earlier version, a possible solution is to get a copy of the Segoe UI Symbol font and install it, and enable the option to replace with a native font in Chromoji. This would allow copy/paste, but the symbols would be monochrome.

In terms of implementation, @RobJDavey, have you considered rendering the emoji as background images instead, and keeping the character inline but invisible? This may allow copy and paste functionality, but would probably require much more work in terms of making sure external styles don't influence the emoji element.

**Comment by RobJDavey** [comment]
@geoffstokes Chrome on Mac does not support the _Apple Color Emoji_ font, it only works natively in Safari.
I have spent some time looking into this issue but not yet found a fix. The problem does not appear to be the copying, but the pasting. I tried to design Chromoji so that when writing in editable field (e.g. the Twitter update box) the emoji rendering is not performed to allow people to send messages. This doesn't seem to be working as well as needed though as it doesn't seem to be detecting the contenteditable for items set to inherit.
I'll try to have another look at a fix for this soon but I'm so busy with other things right now progress is slow.

**Comment by ticky** [comment]
My mistake RE: Chrome and the Emoji font. I'm so used to working in Safari on OS X, where Emoji is supported even within the inspector. :wink:

Thing is, the way this works is embedding an `<img>` tag in place of the emoji character, right? What that means is that if you try to copy it, you're copying an image, not text, and in input boxes which only accept text (i.e. a Twitter client/the Twitter website), you will get the text sans emoji.

From my understanding, the `ContentEditable` issue is _entirely separate_ to that of copy/paste interoperability.

I might get a chance to take a look at this soon, but my proposal would be that we use the native font rendering style, with a span tag and the actual character inside, but style it so the "text" itself is visually hidden, and the `background-image` is the Emoji image.

This way you can get colour emoji everywhere, and copy/paste capability is preserved.
