### ISSUE TITLE
How do I go to the installation?

### ISSUE THREAD

**Issue by jennet735** [locomojis/Chromoji#32]
I installed it, but I don't know how to go to it. Any help will be appreciated.

**Comment by RobJDavey** [comment]
The extension is passive. It will work automatically in the background.
To check it's working go to http://en.wikipedia.org/wiki/Emoji
If you can see emoji instead of squares it's working properly.

If you were hoping for an emoji keyboard so you can type in emoji, this feature is coming but I'm extremely busy at the moment with my real life commitments so it's taking some time.

Thanks for asking for help here, a lot of people do it in reviews where I have no way to contact them :(

**Comment by jennet735** [comment]
ok thank you
